django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('account/', user_views.account, name='account'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('graphic_designs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

graphic_designs/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('product/<slug>/', views.product, name='product'),
    path('add-to-cart/<slug>', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>', views.remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>', views.remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('order-summary/', views.OrderSummaryView.as_view(), name='order-summary'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/<payment_option>/', views.PaymentView.as_view(), name='payment'),
    path('order-confirmation/', views.OrderConfirmationView.as_view(), name='order-confirmation'),
]

graphic_designs/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from users.models import Item

class Review(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    # deletes the post if a user is deleted
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    star_rating = models.CharField(max_length=1)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, default='')

    def __str__(self):
        return self.title

graphic_designs/forms.py
from django import forms
from django_countries.fields import CountryField

PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('O', 'Other')
)

STAR_CHOICES = (
    ('0', 'Please leave a Rating'),
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5')
)

class CheckoutForm(forms.Form):
    street_address = forms.CharField()
    city = forms.CharField()
    country = CountryField(blank_label="Select Country").formfield()
    postcode = forms.CharField()
    same_shipping_address = forms.BooleanField(widget=forms.CheckboxInput(), required=False)
    payment_option = forms.ChoiceField(widget=forms.RadioSelect(), choices=PAYMENT_CHOICES)

class ReviewForm(forms.Form):
    title = forms.CharField()
    review = forms.CharField(widget=forms.Textarea)
    star_rating = forms.ChoiceField(choices=STAR_CHOICES)

graphic_designs/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, View
from django.utils import timezone
from .models import Review
from .forms import CheckoutForm, ReviewForm
from users.models import Item, OrderItem, Order, BillingAddress, Payment

import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.max_network_retries = 2

class HomeView(ListView):
    model = Item
    paginate_by = 12
    template_name = "app/home.html"

class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object':order
            }
            return render(self.request, "app/order_summary.html", context)
        except ObjectDoesNotExist:
            messages.error(self.request, "You do not have an active order")
            return redirect("core:home")
        return render(self.request, "app/order_summary.html")

def product(request, slug):
    item = get_object_or_404(Item, slug=slug)
    review = Review.objects.all()
    form = ReviewForm()
    context = {
        'form': form,
        'item': item,
        'review': review
    }
    return render(request, "app/product.html", context)

@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    # ensure we aren't getting an item that has already been ordered
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False
    )
    # check if item is not already ordered 
    order_query = Order.objects.filter(user=request.user, ordered=False)
    if order_query.exists():
        order = order_query[0]
        # check if order item is in the order 
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.success(request, "This item has been updated in your cart")
            return redirect("core:order-summary")
        else:
            messages.success(request, "This item has been added to your cart")
            order.items.add(order_item)
            return redirect("core:order-summary")
    else: 
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
        messages.success(request, "This item has been added to your cart")
    return redirect("core:order-summary")

@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    # check if item is not already ordered 
    order_query = Order.objects.filter(user=request.user, ordered=False)
    if order_query.exists():
        order = order_query[0]
        # check if order item is in the order 
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            order.items.remove(order_item)
            messages.success(request, "This item has been removed from your cart")
            return redirect("core:order-summary")
        else: 
            messages.error(request, "This item was not in your cart")
            return redirect("core:product", slug=slug)
    else: 
        messages.error(request, "You do not have an active order")
        return redirect("core:product", slug=slug)
    return redirect("core:product", slug=slug)

@login_required
def remove_single_item_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    # check if item is not already ordered 
    order_query = Order.objects.filter(user=request.user, ordered=False)
    if order_query.exists():
        order = order_query[0]
        # check if order item is in the order 
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else: 
                order.items.remove(order_item)
            messages.success(request, "This item quantity has been updated")
            return redirect("core:order-summary")
        else: 
            messages.info(request, "This item was not in your cart")
            return redirect("core:order-summary", slug=slug)
    else: 
        messages.error(request, "You do not have an active order")
        return redirect("core:product", slug=slug)
    return redirect("core:product", slug=slug)

class CheckoutView(View):
    def get(self, *args, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        form = CheckoutForm()
        context = {
            'form': form,
            'order' : order
        }
        return render(self.request, "app/checkout_form.html", context)

    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            if form.is_valid():
                street_address = form.cleaned_data.get('street_address')
                city = form.cleaned_data.get('city')
                country = form.cleaned_data.get('country')
                postcode = form.cleaned_data.get('postcode')
                # TODO: add functionality for these fields 
                # same_shipping_address = form.cleaned_data.get('same_shipping_address')
                payment_option = form.cleaned_data.get('payment_option')
                billing_address = BillingAddress(
                    user=self.request.user,
                    street_address=street_address,
                    city=city,
                    postcode=postcode,
                    country=country,
                )
                billing_address.save()
                order.billing_address = billing_address
                order.save()
                
                if payment_option == 'S':
                    return redirect('core:payment', payment_option='stripe')
                elif payment_option == 'O':
                    return redirect('core:payment', payment_option='other')
                else:
                    messages.warning(self.request, "Invalid payment option")
                    return redirect('core:checkout')
        except ObjectDoesNotExist:
            messages.error(self.request, "You do not have an active order")
            return redirect("core:order-summary")

class PaymentView(View):
    def get(self, *args, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        context = {
            'order':order
        }
        return render(self.request, "app/payment.html", context)

    def post(self, *args, **kwargs):
        # get the order 
        order = Order.objects.get(user=self.request.user, ordered=False)
        # get the token from stripe 
        token = self.request.POST.get('stripeToken')
        # cast as an int to avoid float errors
        amount = int(order.get_total() * 100) # to account for it in pence
        # make the payment intent to stripe 
        charge = stripe.PaymentIntent.create(
            amount=amount,
            currency='gbp',
        )
        # confirm its been ordered
        order.ordered = True 
        # create the payment
        payment = Payment()
        payment.stripe_charge_id = charge['id']
        payment.user = self.request.user
        payment.amount = order.get_total()
        payment.save()
        # assign the payment

        order_items = order.items.all()
        order_items.update(ordered=True)
        for item in order_items:
            item.save()

        order.payment = payment
        order.save()
        
        messages.success(self.request, "Your order was successful!")
        return redirect("core:order-confirmation")

class OrderConfirmationView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        return render(self.request, "app/order_confirmation.html")

        

graphic_designs/templates/app/base.html
{% load static %}
{% load cart_template_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- font awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!-- Bootstrap css -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% if title %}
        <title>Graphic Designs - {{ title }}</title>
    {% else %}
        <title>Graphic Designs</title>
    {% endif %}
    {% block head %}{% endblock %}
</head>
<body>
    <div class="site-header">
        <nav>
            <div class="logo">
                <h4 class="header-text"><a href="{% url 'core:home' %}">Graphic Designs</a></h4>
            </div>
            <ul class="nav-links">
                <li class="navs"><a href="{% url 'core:home' %}">Home</a></li>
                {% if user.is_authenticated %}
                    <li class="navs"><a href="{% url 'account' %}">Account</a></li>
                    <li class="navs"><a href="{% url 'logout' %}">Logout</a></li>
                    <li class="navs"><a href="{% url 'core:order-summary' %}"><i class="fa fa-shopping-cart" aria-hidden="true"></i><span>{{ request.user|cart_item_count }}</span> Cart</a></li>
                {% else %}
                    <li class="navs"><a href="{% url 'login' %}">Login</a></li>
                    <li class="navs"><a href="{% url 'register' %}">Register</a></li>
                {% endif %}
                
            </ul>
            <div class="burger">
                <div class="line1"></div>
                <div class="line2"></div>
                <div class="line3"></div>
            </div>
        </nav>
    </div>
    <div class="messages">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'error'%}
                <div class="alert alert-danger alert-margin">
                    {{ message }}
                </div>
                {% else %}
                    <div class="alert alert-{{ message.tags }} alert-margin">
                        {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
    <div class="slider">
        {% block slider %}{% endblock %}
    </div>
    <div class="container main-content mt-5">
        <div class="row">
            {% block body %}{% endblock %}
        </div>
    </div>
    <footer class="footer py-3">
        <div class="container">
            <span class="text-muted">Check us out on:        
                <i class="fa fa-facebook-official ml-3" aria-hidden="true"></i> 
                <i class="fa fa-instagram" aria-hidden="true"></i> 
                <i class="fa fa-twitter" aria-hidden="true"></i> 
                <i class="fa fa-pinterest-square" aria-hidden="true"></i> 
                <i class="fa fa-youtube-play" aria-hidden="true"></i> 
                <i class="fa fa-google-plus" aria-hidden="true"></i>
            </span>
        </div>
    </footer>
    <!-- footer needed   -->
    <script src="{% static 'js/nav.js' %}"></script>
    <!-- Bootstrap js  -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- vue.js -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    {% block javascripts %}{% endblock %}
</body>
</html>

graphic_designs/templates/app/checkout_form.html
{% extends 'app/base.html' %}
{% load crispy_forms_tags %}

{% block body %}
        <div class="col-md-8 mt-5">
            <form class="mt-1 mr-5 pl-5" action="" method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4"><h1>Checkout Form</h1></legend>
                    {{ form|crispy }}
                </fieldset>
                <button class="btn btn-primary btn-lg btn-block mb-5" type="submit">Continue to Checkout</button>
            </form>
        </div>
        <div class="col-md-4 mt-5">
            <legend class="border-bottom mb-2">Order Summary</legend>
            {% for order_item in order.items.all %}
                <p>{{order_item.quantity }} x {{ order_item.item.title }}: <strong>£{{ order_item.get_final_price }}</strong></p>
            {% endfor %}
            <p>Total: <strong>£{{ order.get_total }}</strong></p>
        </div>
{% endblock %}

graphic_designs/templates/app/home.html
{% extends 'app/base.html' %}

{% block slider %}
<!-- product slider -->
<div id="carousel-example-2" class="carousel slide carousel-fade" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-2" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-2" data-slide-to="1"></li>
        <li data-target="#carousel-example-2" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
            <div class="view">
                <img class="slider-image" style="color:black" src="/media/images/carousel/slider-1.png"
                    alt="First slide">
                <div class="mask rgba-black-light"></div>
            </div>
            <div class="carousel-caption">
                <h3 class="h3-responsive">Welcome to Graphic Designs</h3>
                <p>Check out more awesome designs below <a id="scroll"><i class="fa fa-arrow-down" aria-hidden="true"></i></a></p>
            </div>
        </div>
        <div class="carousel-item">
            <div class="view">
                <img class="slider-image" src="/media/images/carousel/slider-2.png"
                    alt="Second slide">
                <div class="mask rgba-black-strong"></div>
            </div>
            <div class="carousel-caption">
                <p>We also do commissions</p>
            </div>
        </div>
        <div class="carousel-item">
            <div class="view">
                <img class="slider-image" src="/media/images/carousel/slider-3.png"
                    alt="Third slide">
                <div class="mask rgba-black-slight"></div>
            </div>
            <div class="carousel-caption">
                <p>Lorem Ipsum</p>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carousel-example-2" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-2" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
{% endblock %}

{% block body %}
    <!-- product cards  -->
    <div class="col-md-12 mobile-center">
        <br>
        <h1>Our Products & Services</h1>
        <div class="row mobile-center">
        {% for product in object_list %}
            <div class="card mt-5" style="width: 18rem;">
                <a href="{{ product.get_absolute_url }}">
                    <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.title }}">
                </a>
                <div class="card-body">
                    <h5 class="card-title">{{ product.title }}</h5>
                    <p class="card-text">{{ product.description }}</p>
                    <strong class="mr-3">Price: {% if product.discount_price %}£{{ product.discount_price }}{% else %}£{{ product.price }}{% endif %}</strong>
                    <a href="{{ product.get_absolute_url }}" class="btn btn-primary">More Info <i class="fa fa-search" aria-hidden="true"></i></a>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
    <!-- pagination -->
    <div class="col-md-12 mt-4 ml-2">
        <div class="row">
            <ul class="pagination">
                {% if is_paginated %}
                    {% if page_obj.has_previous %}
                        <li class="page-item" id="prev">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous </a>
                        </li>
                    {% endif %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>
                        </li>
                    {% if page_obj.has_next %}
                        <li class="page-item" id="next">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}"> Next</a>
                        </li>
                    {% endif %}
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
<script type="text/javascript">
    if (window.location.href.indexOf("?page") != -1) {
        $("#carousel-example-2").hide();
    }
</script>
{% endblock %}

graphic_designs/templates/app/order_confirmation.html
{% extends 'app/base.html' %}

{% block body %}

    <h1>Great Success</h1>

{% endblock %}

graphic_designs/templates/app/order_summary.html
{% extends 'app/base.html' %}

{% block body %}
    <div class="col-md-12">
        <div class="text-nowrap mt-5 mobile-center">
            <h2>Order Summary</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in object.items.all %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a href="{{ order_item.get_absolute_url }}">{{ order_item.item.title }}</a></td>
                        <td>
                            £{{ order_item.item.price }}
                        </td>
                        <td>
                            <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}">
                                <i class="fa fa-minus-square" aria-hidden="true"></i>
                            </a> 
                            {{ order_item.quantity }} 
                            <a href="{% url 'core:add-to-cart' order_item.item.slug %}">
                                <i class="fa fa-plus-square" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td>
                            {% if order_item.item.discount_price %}
                                £{{ order_item.get_total_discount_price }}
                                <!-- put this in a badge/tag  -->
                                <span class="badge badge-primary">You have saved £{{ order_item.get_savings }}0 woo!</span>
                            {% else %}
                                £{{ order_item.get_total_price }}
                            {% endif %}
                            <a class="float-right text-danger" href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                        <tr>
                            <td colspan="5">Your cart is empty :(</td>
                        </tr>
                        <tr>
                            <td colspan="5">
                                <a href="{% url 'core:home' %}" class="btn btn-primary float-right mr-1">Continue Shopping</a>
                            </td>
                        </tr>
                    {% endfor %}
                    {% if object.get_total %}
                    <tr>
                        <td colspan="4"><strong>Order Total:</strong></td>
                        <td colspan="1">£{{ object.get_total }}</td>
                    </tr>
                    <tr>
                        <td colspan="5" class="mobile-right">
                            <a href="{% url 'core:checkout' %}" class="btn btn-info float-right">Proceed to checkout</a>
                            <a href="{% url 'core:home' %}" class="btn btn-primary float-right mr-1">Continue Shopping</a>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

graphic_designs/templates/app/payment.html
{% extends 'app/base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/stripe.css' %}">
{% endblock %}
{% block body %}
<div class="col-md-8 mt-5">
    <h1>Make Payment</h1>
    
    <form action="." method="POST" id="stripe-form">
        {% csrf_token %}
        <div class="stripe-form-row">
            <label for="card-element">
                Credit or debit card
            </label>
            <div id="card-element">
            <!-- A Stripe Element will be inserted here. -->
            </div>
            <!-- Used to display form errors. -->
            <div id="card-errors" role="alert"></div>
        </div>

        <button class="btn btn-primary mt-2" type="submit">Submit Payment</button>
    </form>
</div>

<div class="col-md-4 mt-5">
    <legend class="border-bottom mb-2">Order Summary</legend>
    {% for order_item in order.items.all %}
        <p>{{order_item.quantity }} x {{ order_item.item.title }}: <strong>£{{ order_item.get_final_price }}</strong></p>
    {% endfor %}
    <p>Total: <strong>£{{ order.get_total }}</strong></p>
</div>
<!-- stripe  -->
<script src="https://js.stripe.com/v3/"></script>
<script src="{% static 'js/stripe.js' %}"></script>
{% endblock %}

graphic_designs/templates/app/product.html
{% extends 'app/base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="col-md-4 mt-5">
        <h1>{{ item.title }}</h1>
        <img class="mt-5" src="{{ item.image.url }}" alt="">
    </div>
    <div class="col-md-8 mb mt-5">
        <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto,
            impedit officiis facere sed blanditiis fugit odio repellat facilis ullam
            unde beatae dolor accusamus modi laborum distinctio hic. Odio, unde labore.
        </p>
        
        {% if item.discount_price %}
            <p><s>Was: £{{ item.price }}</s></p>
            <p><strong>Now: £{{ item.discount_price }}</strong></p>
        {% else %}
            <p>£{{ item.price }}</p>
        {% endif %}
        <a class="btn btn-primary mb-5" href="{{ item.get_add_to_cart_url }}">Add to cart</a>
    </div>
    <div class="col-md-6 mt-5">
        <h2>Customer Reviews</h2>
        {% for comment in review %}
            <legend class="border-bottom mb-2">{{ comment.title }}</legend>
            <div class="star-rating mt-2 mb-2">
                {% if comment.star_rating == '5' %}
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                {% elif comment.star_rating == '4' %}
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                {% elif comment.star_rating == '3' %}
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                {% elif comment.star_rating == '2' %}
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                {% else %}
                    <i class="fa fa-star" aria-hidden="true"></i>
                {% endif %}
            </div>
            <p>{{ comment.content }}</p>
            <div class="border-top pt3 mb-3">
                <small class="text-muted">
                    Review left by: {{ comment.author }} on {{ comment.date_posted|date:'d-m-Y H:i' }}
                </small>
            </div>
        {% endfor %}
    </div>
    <div class="col-md-6 mt-5">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Leave a Review</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
    </div>
    <!-- this needs some stuff on it -->
    
{% endblock %}

{% block javascripts %}
<script>
    var app = new Vue({
        el: '#app',
        // change the default delimiters so it doesn't interfere with jinja 
        delimiters: ['$[', ']'],
        data: {
          message: 'Hello Vue!'
        }
      })
</script>
{% endblock %}